AWSTemplateFormatVersion: '2010-09-09'
Description: Primary Region Setup with EC2 and S3 for Disaster Recovery

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2
      KeyName: your-key-pair
      SecurityGroups:
        - Ref: WebServerSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          echo "Welcome to the Primary Region" > /var/www/html/index.html
          systemctl start httpd
          systemctl enable httpd

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP Access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: primary-region-backup-bucket
